---
title: "DDM Analysis"
author: "Michael P. McDonald"
date: "June 9, 2016"
output: pdf_document
---

Presented here are drift diffusion model parameters generated from Race IAT data collected between February and August 2015.  Parameters are estimated using the analytical "canonical" method.

Note:  All error bars represent +/- 2 SE.

```{r initialize, echo=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(data.table)
library(bit64)
library(tidyr)
library(ggplot2)
library(xtable)
library(knitr)
library(pander)
setwd("..")
source("R/DDMfunctions.R")
source("R/summarySE.R")
source("scripts/performDDManalysis.R")

```

```{r basicPlots, echo=FALSE, warning=FALSE, message=FALSE, results='asis'}

pander(select(DDMv, -ci))
ggplot(DDMv, aes(x=pairingType, y=v, fill=practiceOrTest)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=v-2*se, ymax=v+2*se),
                width=.2,                    # Width of the error bars
                position=position_dodge(.9))
kable(DDMa)

ggplot(DDMa, aes(x=pairingType, y=a, fill=practiceOrTest)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=a-2*se, ymax=a+2*se),
                width=.2,                    # Width of the error bars
                position=position_dodge(.9))
kable(DDMter)

ggplot(DDMter, aes(x=pairingType, y=ter, fill=practiceOrTest)) +
  geom_bar(position=position_dodge(), stat="identity") +
  geom_errorbar(aes(ymin=ter-2*se, ymax=ter+2*se),
                width=.2,                    # Width of the error bars
                position=position_dodge(.9))

```


